import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

const LightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#b183ff',
    surfaceTint: '#266A49',
    onPrimary: '#FFFFFF',
    primaryContainer: '#b183ff',
    onPrimaryContainer: '#FFF',
    secondary: '#b183ff',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#b183ff', //searchbar
    onSecondaryContainer: '#FFF',
    tertiary: '#3C6471',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#BFE9F9',
    onTertiaryContainer: '#234C59',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#93000A',
    background: '#FEF7FF',
    onBackground: '#171D19',
    surface: '#FEF7FF',
    onSurface: '#171D19',
    surfaceVariant: '#d6e1f5',
    onSurfaceVariant: '#404943',
    outline: '#707972',
    outlineVariant: '#C0C9C0',
    shadow: '#000000',
    scrim: '#000000',
    success: '#008000',
    warning: '#F4B400',
    info: '#2196F3', 
    
    inverseSurface: '#2C322E',
    inverseOnSurface: '#EDF2EC',
    inversePrimary: '#91D5AD',
    primaryFixed: '#ACF2C8',
    onPrimaryFixed: '#002112',
    primaryFixedDim: '#91D5AD',
    onPrimaryFixedVariant: '#025233',
    secondaryFixed: '#D0E8D7',
    onSecondaryFixed: '#0B1F15',
    secondaryFixedDim: '#B5CCBB',
    onSecondaryFixedVariant: '#364B3E',
    tertiaryFixed: '#BFE9F9',
    onTertiaryFixed: '#001F28',
    tertiaryFixedDim: '#A4CDDD',
    onTertiaryFixedVariant: '#234C59',
    surfaceDim: '#D6DBD5',
    surfaceBright: '#F6FBF4',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F0F5EE',
    surfaceContainer: '#EAEFE9',
    surfaceContainerHigh: '#E4EAE3',
    surfaceContainerHighest: '#DFE4DD',
  },
};

const DarkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#D5BBFC',
    surfaceTint: '#D5BBFC',
    onPrimary: '#3A255B',
    primaryContainer: '#523C73',
    onPrimaryContainer: '#ECDCFF',
    secondary: '#CEC2DB',
    onSecondary: '#352D40',
    secondaryContainer: '#4C4357',
    onSecondaryContainer: '#EBDEF7',
    tertiary: '#F1B7C3',
    onTertiary: '#4B252E',
    tertiaryContainer: '#643B44',
    onTertiaryContainer: '#FFD9DF',
    error: '#FFB4AB',
    success: '#008000',

    onError: '#690005',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    background: '#151218',
    onBackground: '#E7E0E8',
    surface: '#151218',
    onSurface: '#E7E0E8',
    surfaceVariant: '#4A454E',
    onSurfaceVariant: '#CBC4CF',
    outline: '#958E99',
    outlineVariant: '#4A454E',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#E7E0E8',
    inverseOnSurface: '#322F35',
    inversePrimary: '#6A548D',
    primaryFixed: '#ECDCFF',
    onPrimaryFixed: '#250E45',
    primaryFixedDim: '#D5BBFC',
    onPrimaryFixedVariant: '#523C73',
    secondaryFixed: '#EBDEF7',
    onSecondaryFixed: '#1F182A',
    secondaryFixedDim: '#CEC2DB',
    onSecondaryFixedVariant: '#4C4357',
    tertiaryFixed: '#FFD9DF',
    onTertiaryFixed: '#32101A',
    tertiaryFixedDim: '#F1B7C3',
    onTertiaryFixedVariant: '#643B44',
    surfaceDim: '#151218',
    surfaceBright: '#3B383E',
    surfaceContainerLowest: '#100D12',
    surfaceContainerLow: '#1D1A20',
    surfaceContainer: '#211E24',
    surfaceContainerHigh: '#2C292F',
    surfaceContainerHighest: '#37333A',
  },
};

export { LightTheme, DarkTheme };
